### ISSUE TITLE
using on windows-latest

### ISSUE THREAD

**Issue by Bchir** [actions-go/push#4]
Error: Unable to locate executable file: main_windows.exe. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

**Comment by Bchir** [comment]
also The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by tjamet** [comment]
Thanks for raising!
I am taking a look at it

**Comment by tjamet** [comment]
Hi @Bchir 
This issue should be fixed now. Fixing it in [actions-go/wrapper](https://github.com/actions-go/wrapper/pull/201) revealed a bug on the git windows library, that I work-arounded in #7 

Could you try using `actions-go/push@master` and let me know how this goes for you?
